repos:
  # Terraform formatting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-write=true
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--sort-by-required
          - --args=--sort-inputs-by-required
      - id: terraform_tflint
        args:
          - --args=--only=terraform_deprecated_index
          - --args=--only=terraform_deprecated_interpolation
          - --args=--only=terraform_unused_declarations
          - --args=--only=terraform_comment_syntax
          - --args=--only=terraform_documented_outputs
          - --args=--only=terraform_documented_variables
          - --args=--only=terraform_typed_variables
          - --args=--only=terraform_module_pinned_source
          - --args=--only=terraform_naming_convention
          - --args=--only=terraform_required_version
          - --args=--only=terraform_required_providers
          - --args=--only=terraform_standard_module_structure
      - id: terraform_checkov
        args:
          - --args=--skip-check=CKV_AWS_130
          - --args=--skip-check=CKV_AWS_126
          - --args=--skip-check=CKV_AWS_24
          - --args=--skip-check=CKV_AWS_23
          - --args=--skip-check=CKV_AWS_18
          - --args=--skip-check=CKV_AWS_17
          - --args=--skip-check=CKV_AWS_16
          - --args=--skip-check=CKV_AWS_15
          - --args=--skip-check=CKV_AWS_14
          - --args=--skip-check=CKV_AWS_13
          - --args=--skip-check=CKV_AWS_12
          - --args=--skip-check=CKV_AWS_11
          - --args=--skip-check=CKV_AWS_10
          - --args=--skip-check=CKV_AWS_9
          - --args=--skip-check=CKV_AWS_8
          - --args=--skip-check=CKV_AWS_7
          - --args=--skip-check=CKV_AWS_6
          - --args=--skip-check=CKV_AWS_5
          - --args=--skip-check=CKV_AWS_4
          - --args=--skip-check=CKV_AWS_3
          - --args=--skip-check=CKV_AWS_2
          - --args=--skip-check=CKV_AWS_1
          - --args=--skip-check=CKV_AWS_130
          - --args=--skip-check=CKV_AWS_126
          - --args=--skip-check=CKV_AWS_24
          - --args=--skip-check=CKV_AWS_23
          - --args=--skip-check=CKV_AWS_18
          - --args=--skip-check=CKV_AWS_17
          - --args=--skip-check=CKV_AWS_16
          - --args=--skip-check=CKV_AWS_15
          - --args=--skip-check=CKV_AWS_14
          - --args=--skip-check=CKV_AWS_13
          - --args=--skip-check=CKV_AWS_12
          - --args=--skip-check=CKV_AWS_11
          - --args=--skip-check=CKV_AWS_10
          - --args=--skip-check=CKV_AWS_9
          - --args=--skip-check=CKV_AWS_8
          - --args=--skip-check=CKV_AWS_7
          - --args=--skip-check=CKV_AWS_6
          - --args=--skip-check=CKV_AWS_5
          - --args=--skip-check=CKV_AWS_4
          - --args=--skip-check=CKV_AWS_3
          - --args=--skip-check=CKV_AWS_2
          - --args=--skip-check=CKV_AWS_1

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml]

  # Shell script formatting
  - repo: https://github.com/pre-commit/mirrors-shfmt
    rev: v3.7.0
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
