name: Generate Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.0"

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Generate Module Documentation
        run: |
          # Generate docs for each module
          for module in modules/*/; do
            if [ -d "$module" ]; then
              echo "Generating docs for module: $module"
              terraform-docs markdown table --output-file README.md --output-mode inject "$module"
            fi
          done

      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: auto-generate documentation"
          title: "📚 Auto-generate documentation"
          body: |
            This PR contains automatically generated documentation updates.
            
            Changes include:
            - Updated README.md with latest input/output documentation
            - Updated module documentation
            - Generated by terraform-docs
            
            Please review the changes and merge if everything looks correct.
          branch: docs/auto-update
          delete-branch: true
